### PR TITLE
Fix broken link in documentation

### PR DESCRIPTION
**Pull request by alexadrien**
In this documentation page : https://use-gesture.netlify.app/docs/motivation/
The link between "trigger logic when the gesture starts or ends out of the box" is broken
It might be because of the line break on line 22 ?

### CODE REVIEW

**Comment by dbismut** [comment]
Hi, thanks for spotting the issue. I think it's related to the fact that I'm using an Easter egg wherever I mention React UseGesture. 

It's actually a draggable component and its hand emoji changes every time you load the page. I guess no one noticed but anyway. 

But the fact that it's positioned as the *first* element of the paragraph messes with MDX which considers the whole paragraph as JSX and not markdown. 

I think the way to fix this at this point is to uses `<code>` tags instead of ticks and an actual `<a>` tag for the link.

**Comment by dbismut** [comment]
Turns out adding `&zwnj;` at the beginning of the line is enough :)

**Comment by alexadrien** [comment]
> Hi, thanks for spotting the issue. I think it's related to the fact that I'm using an Easter egg wherever I mention React UseGesture.
> 
> It's actually a draggable component and its hand emoji changes every time you load the page. I guess no one noticed but anyway.
> 
> But the fact that it's positioned as the _first_ element of the paragraph messes with MDX which considers the whole paragraph as JSX and not markdown.
> 
> I think the way to fix this at this point is to uses `<code>` tags instead of ticks and an actual `<a>` tag for the link.

The easter egg is noticed ;) I love it

**Comment by alexadrien** [comment]
> Turns out adding `&zwnj;` (invisible character) at the beginning of the line is enough :)

Awesome that you found a fix ! Thanks for your work on this library, it is so cool

**Comment by dbismut** [comment]
Thanks! I'll fix this as part as upcoming v8.1 which should be around the corner hopefully this week!

**Pull request closed without merging**
